@jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdHVkZW50X2lkIjoxLCJleHAiOjE2NzIxOTQ4NjN9.GE5nre7a0JoCzVfs7eA-426Ai7RgW9YkqS9F-IOaLzo

### Users create (signup)
POST http://localhost:3000/students.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
