### Students Index
GET http://localhost:3000/students.json

@jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdHVkZW50X2lkIjoxLCJleHAiOjE2NzIyODMwOTZ9.EfoOArjCz5g0MzmuK6vJE9Dou8hJfsddarR8yvV1ToU

### Users create (signup)
POST http://localhost:3000/students.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


### Experience create
POST http://localhost:3000/experiences.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "start_date": "2018-01-01",
  "end_date": "2020-01-02",
  "job_title": "Technician",
  "company_name": "Gillette",
  "details": "Working on a factory floor creating razor blades for Fusion line products."
}

### Experience update
PATCH http://localhost:3000/experiences/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "start_date": "2018-01-01",
  "end_date": "2020-01-02",
  "job_title": "Lead Technician",
  "company_name": "Gillette",
  "details": "Working on a factory floor creating razor blades for Fusion line products."
}

